# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-11 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('average_score', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Activity_mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_score', models.FloatField(default=0)),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contestdata.Activities')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=200)),
                ('average_score', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contestdata.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor_Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contestdata.Mentor')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='mentor_team',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contestdata.Teams'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contestdata.Teams'),
        ),
        migrations.AddField(
            model_name='candidate_team',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contestdata.Teams'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contestdata.Teams'),
        ),
        migrations.AddField(
            model_name='activity_mentor',
            name='mentor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contestdata.Mentor'),
        ),
    ]
