# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-12 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contestdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor_team',
            name='mentor_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contestdata.Mentor'),
        ),
        migrations.AlterField(
            model_name='mentor_team',
            name='team_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contestdata.Teams'),
        ),
    ]
