# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-12 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contestdata', '0002_auto_20170612_2134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
    ]
