# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-12 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contestdata', '0003_auto_20170612_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='candidate',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='contestdata.Candidate'),
        ),
    ]
