# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-12 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contestdata', '0005_remove_mentor_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor_team',
            name='mentor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contestdata.Mentor'),
        ),
    ]
