# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-12 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contestdata', '0006_auto_20170613_0102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='average_score',
            new_name='Score',
        ),
    ]
