# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-12 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestdata', '0009_remove_activities_average_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='activity_score',
            field=models.FloatField(default=0),
        ),
    ]
