# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-14 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestdata', '0010_activities_activity_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='id',
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
