# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-14 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contestdata', '0012_auto_20170614_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contestdata.Candidate'),
        ),
    ]
