# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-15 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contestdata', '0013_auto_20170615_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transition_date', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contestdata.DeviceModel')),
            ],
            options={
                'db_table': 'History',
            },
        ),
        migrations.AlterModelTable(
            name='activities',
            table='Activities',
        ),
        migrations.AlterModelTable(
            name='activity_mentor',
            table='ActivityMentor',
        ),
        migrations.AlterModelTable(
            name='candidate',
            table='Candidate',
        ),
        migrations.AlterModelTable(
            name='candidate_team',
            table='CandidateTeam',
        ),
        migrations.AlterModelTable(
            name='mentor',
            table='Mentor',
        ),
        migrations.AlterModelTable(
            name='mentor_team',
            table='MentorTeam',
        ),
        migrations.AlterModelTable(
            name='team',
            table='Team',
        ),
    ]
