# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-15 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contestdata', '0014_auto_20170615_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='device',
        ),
        migrations.DeleteModel(
            name='DeviceModel',
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
