# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-15 17:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contestdata', '0015_auto_20170615_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='date_performed',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 15, 17, 37, 44, 200216, tzinfo=utc)),
        ),
    ]
