# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-15 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contestdata', '0017_auto_20170615_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='date_performed',
        ),
    ]
