# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-15 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestdata', '0020_remove_activities_date_performed'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='date_performed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
