# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-15 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestdata', '0027_remove_activities_activity_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=64)),
                ('user_type', models.CharField(max_length=200)),
            ],
        ),
    ]
