# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-16 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestdata', '0028_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='average_score',
            field=models.FloatField(db_column='average_score', default=0),
        ),
    ]
