# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-16 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestdata', '0030_auto_20170616_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='average_score',
        ),
        migrations.AddField(
            model_name='activities',
            name='average_score',
            field=models.FloatField(default=0),
        ),
    ]
