# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-16 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contestdata', '0031_auto_20170616_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='average_score',
            new_name='activity_score',
        ),
    ]
