# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-17 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestdata', '0035_activities_activity_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='activity_score',
            field=models.FloatField(db_column='activity_score', default=0),
        ),
    ]
