# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-17 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestdata', '0036_auto_20170617_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='activity_score',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='average_score',
        ),
        migrations.AddField(
            model_name='activities',
            name='activityScore',
            field=models.FloatField(db_column='activityScore', default=0),
        ),
    ]
