# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-17 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestdata', '0037_auto_20170617_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='activityScore',
        ),
        migrations.AddField(
            model_name='activities',
            name='activity_score',
            field=models.FloatField(db_column='activity_score', default=0),
        ),
    ]
