# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-17 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestdata', '0041_remove_activities_average_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='average_score',
            field=models.FloatField(default=0),
        ),
    ]
