# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-18 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contestdata', '0043_remove_activities_average_score'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='member',
            table='Member',
        ),
    ]
